name: Upload to S3
on: 
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2
  IAM_ROLE: arn:aws:iam::852587482157:role/GithubActionDeployWebsite
  BUCKET_NAME: aboods-portfolio-site
  NODE_VERSION: 18.12.1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build Project
        run: npm ci && npm run build --if-present
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Push to S3
        run: aws s3 sync ./build s3://${{ env.BUCKET_NAME }} --delete --quiet
